import day08
import gleam/string
import gleeunit/should

pub fn day08_test() {
  let s =
    "
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
"
    |> string.trim
  day08.part1(s) |> should.equal(Ok("14"))
  day08.part2(s) |> should.equal(Ok("34"))
}
